language: java
jdk: oraclejdk8
sudo: false
script: mvn package

deploy:
  skip_cleanup: true
  provider: s3
  bucket: gamecard
  region: us-east-1
  access_key_id: AKIAJVHAVDNVK6G5YA4A
  secret_access_key:
    secure: OgUjthxpCqLcYtcgavB7JmkFXB3mH9QZfVdmc2R/8ohjdwyKa2OZL89B9KcR3Af8CBCEsyQM5jb6fkgX9romQ2a7JkVGKmJcj03ZdhmkYNES0RPHtoVfBR8bcZZUz7koGxlfAvrt3QEiE/MH10gOV7+JTafxdtrAbuRfRceZBBsFNdplXSwufJAbUyrc970NfiJMkqXVGwQ6ouxXBpYnHE3Zf7OHVvxSO8BTmh932wcdR1JCJ9R2Dhe3sxgHcLNgdg3OzDs2ekvP4DWvwMzqAgVUkKoBsD5IP5ncJC6Nt8EUhaSsPPT0QJxobBv+h7025x0zNiJULQkVdmbqGApxpwo9gFlHfBu8R11CqHRZP+n44JNNeO0T0QYX6ExxF4T78xPDQu/BfYuK7frftWBOiHaKxFEjHaz75VqbathCUZx7pJO3iZ2bAkbWVt0lYVJOgb12VsCsrI4ztMjmCIqZlkoGCISPjj1bmGMBrO1K+RDSO8ZGVYekYMKh1jfTuQGdWkCEfCnXQwLtLdQZ/mo537UAkwhmr9gE9X205hTTKau32/dJHWt1qzScssI6aC89IYWjJRwmk6gCQ0DMAUo12y2wh+mB2HxaPrQKrB3ITnWI63Xesp4gdU8+KHjR7rzPxSvTe2YEefN10HvYyX3xCdkaf5tnBY7Fw/L3DC05SwM=
addons:
  sonarqube:
    organization: mmueller86-github
    token:
      secure: "Pr7pQBRQcY2xQl9K5rJAsl9JNYQtK0tKu8YTj7bhawfE60JhfW06H80RK7zceDfQDJY1StJc1BebE22CL2pDCCFoRRkz99x4Sryl1R8Wal94Vdue4oRAIziLekhnd3hUgEiaATO7I52F7TIWx8BcMp45TobeExxFXlLqfDUJlXIfEJIwB22v571/4lE0e2/b9vJdQkoTG9/nYOGo4JNRM5CSIu1Xop2jkm+uV/5UW4bav8IdlwLvRA6Qns+oI8ZZorW54wqYwd5HxkOkFKSo8d5zojaWZAv2eckq9yo9x6HdrkCXv1dqi5nQMay5KiDcfI4p0fTWzp8AxsPGM/J1pc2nOF/UzICpiiZLxgQ2iwL5HPAraru7ZEYLob1JsQ1e17MXepiwPmRmmENkPrzI/kg9+dcDoe7038bGLGnQ/Q/qpsfJX4+AiW20HU1+uFTP0NkPhGol504zGIewZyOaoZAAH0jRdCdQxXIKXWv2pV2L8p4awnjnEMUjapoIy9K6VFld92KPivmc/tHUSxm18rNQlXXt/6r+wQrEXxNgb6ATmErGEUbI7m0DzqHYXB//5IsLsNNSL88POKYB5JATpPzxdtEmVwOw/vjTtEcq/3QLZkgeKTPV/z1sKvwYgAe9J77pVtX9/EEg63pG4lLBwwNIV5BKDfKHW7YGo3HS4mE="
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner